### PR TITLE
GeneSetCollections => GeneSetGroups

### PR DESCRIPTION
**Pull request by mokolodi1**

### CODE REVIEW

**Comment by e-t-k** [comment]
lgtm.

**Comment by e-t-k** [comment]
[ ] update Medbook docker-compose.yml with reference to new filename
[ ] update patient-care, job-runner etc with references to new environment variable (I'm assuming you're renaming "gene_set_collection_export" to "gene_set_group_export"

**Comment by mokolodi1** [comment]
@e-t-k I'm doing those things now!

**Comment by mokolodi1** [comment]
See here: https://github.com/UCSC-MedBook/MedBook/commit/81e16e41a4992b0184563cf4c76e8636192c5570

**Pull request merged**
